name: Cypress Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código do repositório do frontend
      uses: actions/checkout@v2
      
    - name: Checkout do código do repositório de testes
      uses: actions/checkout@v2
      with:
        repository: S204-Inatel-2024-1/Ewel_e_Amigos_Tests_Cypress
        path: cypress_tests  # Define o diretório onde o repositório será clonado

    - name: Instalar dependências
      working-directory: ./cypress_tests  # Define o diretório onde os comandos serão executados
      run: npm install

    - name: Rodar testes Cypress
      working-directory: ./cypress_tests  # Define o diretório onde os testes serão executados
      run: npm run test:cypress -- --env REPO_URL=https://github.com/S204-Inatel-2024-1/Ewel_e_Amigos_Tests_Cypress

    - name: Upload Cypress videos
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-videos
        path: cypress_tests/cypress/videos

    - name: Upload Cypress screenshots
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-screenshots
        path: cypress_tests/cypress/screenshots

    - name: Upload Cypress reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: cypress-reports
        path: cypress_tests/cypress/reports
